### ISSUE TITLE
Incorrect MCQs

### ISSUE THREAD

**Issue by vital987** [kishanrajput23/NPTEL-The-Joy-of-Computing-using-Python#10]
Hello Kishan,
Week-5 assignment Q8 & Q9 are incorrect, I request you to verify answers and then post them.
Regards, 
Apoorv Vyavahare

**Comment by kishanrajput23** [comment]
Hello Apoorv,

I posted all the correct answer after verifying.
If you didn't know Nptel has already said that they will not consider Q9 for evaluation just because Q9 has incorrect options and for Q8 you can check out on google that my option is correct but, sometimes nptel has its own choice that which option they're assuming correct for particular question.

For more information you can check nptel discussion group where every person are asking about Q8 clarification because most of the students selected option B. 

I think you got 80 in Week 5 Assignment but do not worry about that after somedays your score will change and most probably it will be 90 out 100 or may be 100 out of 100.

The most important thing is that for final exam your best 8 assignments will consider not all 12 so, just chill it's just a beginning of the course and I always tried my best.

Hope you understand!!

**Comment by vital987** [comment]
Hello Kishan,
I understand the things and thanks for the cooperation. 
Regards,
Apoorv Vyavahare

**Comment by kishanrajput23** [comment]
You're welcome.
