### ISSUE TITLE
Previous Year Question Papers

### ISSUE THREAD

**Issue by Lakhankumawat** [kishanrajput23/NPTEL-The-Joy-of-Computing-using-Python#6]
## I would like to suggest to add these.
1. Previous Year Question Papers for this course
2. A README inside Previous Year Question Paper Giving a brief overview of exam question paper pattern type and scores divided.

**Comment by Lakhankumawat** [comment]
> ## I would like to suggest to add these.
> 1. Previous Year Question Papers for this course
> 2. A README inside Previous Year Question Paper Giving a brief overview of exam question paper pattern type and scores divided.

Although i can create a PR for second one  , but for first one i searched most of google but was hardly able to find any prev. year que. papers .

**Comment by kishanrajput23** [comment]
Yes I also searched on google but, can't able to find previous year question papers for this course. Actually, NPTEL never release proctored exam question paper.

Apart from this they release previous year weekly quizzes questions with solution so that once can learn and practice from that quizzes. Because most of the questions come from these weekly quizzes.

For now if you want to create PR for 2nd one you can.
